import Head from "next/head";
import Image from "next/image";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={`${montserrat.className} mx-16 my-12`}>
        <nav>
          <center>
            <Image
              width={100}
              height={200}
              src="/next.svg"
              alt="Logo"
              color="white"
            ></Image>
          </center>
        </nav>
        {children}
      </body>
    </html>
  );
}
